<?php
namespace yii\easyii2\modules\article\controllers;

use yii\easyii2\components\ActiveRecord;
use yii\easyii2\components\CategoryController;

class AController extends CategoryController
{

    /** @var string  */
    public $moduleName = 'article';

    public function init()
    {
        $this->categoryClass = ActiveRecord::getModelByName('Category', 'article');
        parent::init(); // TODO: Change the autogenerated stub
    }

}