<?php
namespace yii\easyii2\components;

use app\modules\lang\models\Lang;
use Yii;
use yii\easyii2\AdminModule;
use yii\helpers\ArrayHelper;

class FastModule extends Module
{
    //public $controllerNamespace = 'grozzzny\base_module\controllers';

    public $controllerMap = [
        'a' => 'yii\easyii2\controllers\FastController',
    ];

    public function init()
    {
        self::setView($this->viewPath);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getModels()
    {
        $models = [];
        $adminModule = AdminModule::getInstance();
        $settings = empty($adminModule) ? $this->settings : $adminModule->getModule(Yii::$app->controller->module->id)->settings;

        foreach (glob($this->basePath . "/models/*.php") as $file){
            $file_name = basename($file, '.php');

            if($file_name == 'Base') continue;

            $alternative_class_name = ArrayHelper::getValue($settings, 'model'.$file_name, '');

            $class_name = !empty($alternative_class_name) ? $alternative_class_name : preg_replace('/[^\\\]+$/', '', $this->className()) . 'models\\' . $file_name;

            if(!class_exists($class_name)) continue;

            $class = Yii::createObject($class_name);

            if(!$class::PRIMARY_MODEL) continue;

            $models[$class::getSlugModel()] = $class;
        }

        return $models;
    }

    /**
     * @param $slug
     * @return FastModel|FastModelInterface
     */
    public function getModelBySlug($slug)
    {
        $models = $this->getModels();
        return empty($slug) ? current($models) : $models[$slug];
    }

    public static function setView($view)
    {
        if(!$pathMap = Yii::$app->view->theme->pathMap) return false;

        if(empty($pathMap)) return false;

        if(key_exists('@vendor/grozzzny/easyii2/views', $pathMap)){
            array_push(Yii::$app->view->theme->pathMap['@vendor/grozzzny/easyii2/views'], $view);
        }else{
            Yii::$app->view->theme->pathMap['@vendor/grozzzny/easyii2/views'] = $view;
        }
    }

}